#!/bin/bash

# Install battery, configuration tools 
sudo apt-get install -y smartmontools tlp tlp-rdw lm-sensors powertop htop

sudo apt install fasd # haven't tried this. 
sudo apt install httpie # haven't tried this. 

## Install snaps
sudo apt install snapd

sudo snap install chromium
sudo snap install tor
sudo snap install snap-store

## Install copyq, allows you to multi copy and paste from the clipboard
sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install copyq

# work
sudo snap install zenkit
# sudo snap install wavebox ## multi apps client
# sudo snap install tusk ## evernote client
sudo snap install espanso --classic --channel=latest/edge ## text expander

# cloud 
sudo snap install aws-cli --classic
sudo snap install heroku --classic

#development
sudo snap install universal-ctags
sudo snap connect universal-ctags:dot-ctags

sudo snap install code --classic
sudo snap install docker
sudo snap install cacher
sudo snap install dataexplore
sudo snap install insomnia
sudo snap install ripgrep --classic
sudo snap install beekeeper-studio # sql client 
sudo snap install robo3t-snap # mongo client 

sudo apt-get install vim xclip git

# photo/video
sudo snap install blender --classic
sudo snap install photoscape
sudo snap install polarr

#audio, news 
sudo snap install poddr
sudo snap install raven-reader


#### Add repos
sudo add-apt-repository ppa:w-vollprecht/ppa

# dropbox

sudo add-apt-repository -y "deb http://archive.canonical.com/ $(lsb_release -sc) partner"


# chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb



# basic update
sudo apt-get -y update
sudo apt-get -y upgrade

    sudo apt-get install apt-transport-https ca-certificates


# install apps
sudo apt-get -y install \
    libxss1 filezilla \
    p7zip p7zip-full p7zip-rar  \
    indicator-multiload gparted dkms \
    mcrypt ssmtp mailutils mpack truecrypt \
    linux-headers-generic \
    tp-smapi-dkms tuxguitar
    
# install dev apps 
sudo apt-get -y install git gitk gitg build-essential python3-dev python3-pip curl nodejs guake python-is-python3 \ 
    silversearcher-ag zsh fonts-powerline libpq-dev xsel 
# DOCKER
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(. /etc/os-release; echo "$UBUNTU_CODENAME") stable"
sudo apt-get update
sudo apt-get -y  install docker-ce docker-compose

sudo usermod -aG docker $USER

sudo apt-get install postgresql-client-common postgresql postgresql-contrib 

# not snaps
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

# ruby
sudo apt install rbenv
mkdir -p "$(rbenv root)"/plugins
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
rbenv install 2.7.1
rbenv rehash 

gem install bundler

##### tmux
VERSION=3.1
sudo apt-get -y remove tmux
sudo apt-get -y install wget tar libevent-dev libncurses-dev
wget https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz
tar xf tmux-${VERSION}.tar.gz
rm -f tmux-${VERSION}.tar.gz
cd tmux-${VERSION}
./configure
make
sudo make install
cd -
sudo rm -rf /usr/local/src/tmux-*
sudo mv tmux-${VERSION} /usr/local/src

# 

# fasd, for fast search dirs and files 
sudo add-apt-repository ppa:aacebedo/fasd
sudo apt-get update
sudo apt-get install fasd

#### DATA 

## jupyter
pip3 install jupyter bpython ipython pandas numpy scipy matplotlib torch tensorflow scikit-learn 




## Rust

curl https://sh.rustup.rs -sSf | sh 